language: swift
os: osx
osx_image: xcode11

# ------
# ADDONS
# ------

addons:
  homebrew:
    packages:
    - swiftlint
    update: true

# ----
# JOBS
# ----

jobs:
  include:
    - stage: build_release
      name: Build frameworks and XCFramework
      script:
        - >
          xcodebuild archive \
            -scheme CocoaTypograf-iOS \
            -archivePath ./build/ios/ios.xcarchive\
            -sdk iphoneos \
            SKIP_INSTALL=NO | xcpretty
        - >
          xcodebuild archive \
            -scheme CocoaTypograf-iOS \
            -archivePath ./build/ios/ios_sim.xcarchive \
            -sdk iphonesimulator \
            SKIP_INSTALL=NO | xcpretty
        - >
          xcodebuild archive \
            -scheme CocoaTypograf-macOS \
            -archivePath ./build/macos/macos.xcarchive \
            SKIP_INSTALL=NO | xcpretty
        - >
          xcodebuild -create-xcframework \
            -framework ./build/ios/ios.xcarchive/Products/Library/Frameworks/CocoaTypograf.framework \
            -framework ./build/ios/ios_sim.xcarchive/Products/Library/Frameworks/CocoaTypograf.framework \
            -framework ./build/macos/macos.xcarchive/Products/Library/Frameworks/CocoaTypograf.framework \
            -output ./build/CocoaTypograf.xcframework | xcpretty

# ------
# STAGES
# ------

stages:
  - name: create_release
    if: branch = develop
  - name: build_release
    if: tag =~ /^\d+\.\d+\.\d+?/

