//
//  EntityType.swift
//  CocoaTypograf
//
//  Created by Vadim Zhilinkov on 04/09/2018.
//  Copyright © 2018 dreadct. All rights reserved.
//

import Foundation

/// Specifies entity types to be generated by a service.
public enum EntityType: Int {
    /// No entities will be generated — only plain text.
    case none = 3
    /// HTML entities will be generated.
    case html = 1
    /// XML entities will be generated.
    case xml = 2
    /// Mixed (HTML and XML) entities will be generated.
    case mixed = 4
}
